/**
 * Static tool definition catalog — discovery cold path.
 *
 * Generated by scripts/generate-tool-definitions.ts.
 * Importing this module does NOT load tool execute implementations.
 */

import type { ToolParametersSchema } from "./tool-types";
import { astGrepDefinition } from "./tools/definitions/ast_grep.definition";
import { attackSurfaceScanDefinition } from "./tools/definitions/attack_surface_scan.definition";
import { authAuditDefinition } from "./tools/definitions/auth_audit.definition";
import { autoPatchDefinition } from "./tools/definitions/auto_patch.definition";
import { browserProberDefinition } from "./tools/definitions/browser_prober.definition";
import { candidateRevalidatorDefinition } from "./tools/definitions/candidate_revalidator.definition";
import { containerAuditDefinition } from "./tools/definitions/container_audit.definition";
import { credsValidatorDefinition } from "./tools/definitions/creds_validator.definition";
import { cveAuditDefinition } from "./tools/definitions/cve_audit.definition";
import { deepAnalysisPipelineDefinition } from "./tools/definitions/deep_analysis_pipeline.definition";
import { dependencyCheckDefinition } from "./tools/definitions/dependency_check.definition";
import { detectWorkspaceCapabilitiesDefinition } from "./tools/definitions/detect_workspace_capabilities.definition";
import { duDefinition } from "./tools/definitions/du.definition";
import { entropyScanDefinition } from "./tools/definitions/entropy_scan.definition";
import { envAuditDefinition } from "./tools/definitions/env_audit.definition";
import { eslintScanDefinition } from "./tools/definitions/eslint_scan.definition";
import { evidencePackDefinition } from "./tools/definitions/evidence_pack.definition";
import { fileEditorDefinition } from "./tools/definitions/file_editor.definition";
import { fileMetadataDefinition } from "./tools/definitions/file_metadata.definition";
import { findDefinition } from "./tools/definitions/find.definition";
import { findSimilarFailuresDefinition } from "./tools/definitions/find_similar_failures.definition";
import { flowTraceDefinition } from "./tools/definitions/flow_trace.definition";
import { fuzzerDefinition } from "./tools/definitions/fuzzer.definition";
import { gitDiagDefinition } from "./tools/definitions/git_diag.definition";
import { gitForensicsDefinition } from "./tools/definitions/git_forensics.definition";
import { globDefinition } from "./tools/definitions/glob.definition";
import { httpProberDefinition } from "./tools/definitions/http_prober.definition";
import { jsonProbeDefinition } from "./tools/definitions/json_probe.definition";
import { jwtDecoderDefinition } from "./tools/definitions/jwt_decoder.definition";
import { localNetworkReconDefinition } from "./tools/definitions/local_network_recon.definition";
import { lsDefinition } from "./tools/definitions/ls.definition";
import { mockPoisonDefinition } from "./tools/definitions/mock_poison.definition";
import { mutationDefinition } from "./tools/definitions/mutation.definition";
import { networkMapDefinition } from "./tools/definitions/network_map.definition";
import { oobListenerDefinition } from "./tools/definitions/oob_listener.definition";
import { packageAuditDefinition } from "./tools/definitions/package_audit.definition";
import { pdfSecurityReportDefinition } from "./tools/definitions/pdf_security_report.definition";
import { planValidationDefinition } from "./tools/definitions/plan_validation.definition";
import { prototypePollutionFuzzerDefinition } from "./tools/definitions/prototype_pollution_fuzzer.definition";
import { pwdDefinition } from "./tools/definitions/pwd.definition";
import { readDefinition } from "./tools/definitions/read.definition";
import { readManyDefinition } from "./tools/definitions/read_many.definition";
import { recordFailureDefinition } from "./tools/definitions/record_failure.definition";
import { recordResolutionDefinition } from "./tools/definitions/record_resolution.definition";
import { redosAnalyzerDefinition } from "./tools/definitions/redos_analyzer.definition";
import { repoGraphDefinition } from "./tools/definitions/repo_graph.definition";
import { rgDefinition } from "./tools/definitions/rg.definition";
import { runTestsDefinition } from "./tools/definitions/run_tests.definition";
import { sandboxRunDefinition } from "./tools/definitions/sandbox_run.definition";
import { secretScanDefinition } from "./tools/definitions/secret_scan.definition";
import { securityAuditDefinition } from "./tools/definitions/security_audit.definition";
import { securityPathTraceDefinition } from "./tools/definitions/security_path_trace.definition";
import { securityReportDefinition } from "./tools/definitions/security_report.definition";
import { semgrepScanDefinition } from "./tools/definitions/semgrep_scan.definition";
import { sourceMapAnalyzerDefinition } from "./tools/definitions/source_map_analyzer.definition";
import { sqlAuditDefinition } from "./tools/definitions/sql_audit.definition";
import { supermemoryDefinition } from "./tools/definitions/supermemory.definition";
import { threatModelDefinition } from "./tools/definitions/threat_model.definition";
import { trafficPoisonDefinition } from "./tools/definitions/traffic_poison.definition";
import { treeDefinition } from "./tools/definitions/tree.definition";
import { verifyValidationPersistenceDefinition } from "./tools/definitions/verify_validation_persistence.definition";

export interface StaticToolDefinition {
  name: string;
  description: string;
  parameters: ToolParametersSchema;
  aliases: readonly string[];
}

export const STATIC_TOOL_DEFINITIONS: readonly StaticToolDefinition[] = [
  astGrepDefinition,
  attackSurfaceScanDefinition,
  authAuditDefinition,
  autoPatchDefinition,
  browserProberDefinition,
  candidateRevalidatorDefinition,
  containerAuditDefinition,
  credsValidatorDefinition,
  cveAuditDefinition,
  deepAnalysisPipelineDefinition,
  dependencyCheckDefinition,
  detectWorkspaceCapabilitiesDefinition,
  duDefinition,
  entropyScanDefinition,
  envAuditDefinition,
  eslintScanDefinition,
  evidencePackDefinition,
  fileEditorDefinition,
  fileMetadataDefinition,
  findDefinition,
  findSimilarFailuresDefinition,
  flowTraceDefinition,
  fuzzerDefinition,
  gitDiagDefinition,
  gitForensicsDefinition,
  globDefinition,
  httpProberDefinition,
  jsonProbeDefinition,
  jwtDecoderDefinition,
  localNetworkReconDefinition,
  lsDefinition,
  mockPoisonDefinition,
  mutationDefinition,
  networkMapDefinition,
  oobListenerDefinition,
  packageAuditDefinition,
  pdfSecurityReportDefinition,
  planValidationDefinition,
  prototypePollutionFuzzerDefinition,
  pwdDefinition,
  readDefinition,
  readManyDefinition,
  recordFailureDefinition,
  recordResolutionDefinition,
  redosAnalyzerDefinition,
  repoGraphDefinition,
  rgDefinition,
  runTestsDefinition,
  sandboxRunDefinition,
  secretScanDefinition,
  securityAuditDefinition,
  securityPathTraceDefinition,
  securityReportDefinition,
  semgrepScanDefinition,
  sourceMapAnalyzerDefinition,
  sqlAuditDefinition,
  supermemoryDefinition,
  threatModelDefinition,
  trafficPoisonDefinition,
  treeDefinition,
  verifyValidationPersistenceDefinition,
].map((def) => ({
  name: def.name,
  description: def.description,
  parameters: def.parameters,
  aliases: def.aliases,
}));

const byName = new Map<string, StaticToolDefinition>();
const byAlias = new Map<string, StaticToolDefinition>();

for (const def of STATIC_TOOL_DEFINITIONS) {
  byName.set(def.name, def);
  byAlias.set(def.name, def);
  for (const alias of def.aliases) {
    byAlias.set(alias, def);
  }
}

export function listStaticToolDefinitions(): readonly StaticToolDefinition[] {
  return STATIC_TOOL_DEFINITIONS;
}

export function getStaticToolDefinition(
  nameOrAlias: string,
): StaticToolDefinition | undefined {
  return byAlias.get(nameOrAlias) ?? byName.get(nameOrAlias);
}

export function getStaticToolDefinitionCount(): number {
  return STATIC_TOOL_DEFINITIONS.length;
}
