import type { ToolLoader } from "./tool-types";

/**
 * Lazy tool loaders.
 *
 * Each entry is [registryKey, loader]. Where the historical short alias differs
 * from the canonical tool.name exposed to agents, BOTH keys are registered so
 * resolution never fails for either form.
 */
export const lazyToolLoaders: Array<[string, ToolLoader]> = [
  ["rg", () => import("./tools/rg").then((m) => m.rgTool)],
  ["ls", () => import("./tools/ls").then((m) => m.lsTool)],
  ["read", () => import("./tools/read").then((m) => m.readTool)],
  ["git", () => import("./tools/git").then((m) => m.gitTool)],
  ["git_diag", () => import("./tools/git").then((m) => m.gitTool)],
  ["secrets", () => import("./tools/secrets").then((m) => m.secretScanTool)],
  ["secret_scan", () => import("./tools/secrets").then((m) => m.secretScanTool)],
  ["metadata", () => import("./tools/metadata").then((m) => m.fileMetadataTool)],
  ["file_metadata", () => import("./tools/metadata").then((m) => m.fileMetadataTool)],
  ["tree", () => import("./tools/tree").then((m) => m.projectTreeTool)],
  ["audit", () => import("./tools/audit").then((m) => m.securityAuditTool)],
  ["security_audit", () => import("./tools/audit").then((m) => m.securityAuditTool)],
  ["deps", () => import("./tools/deps").then((m) => m.dependencyAnalyzerTool)],
  ["dependency_check", () => import("./tools/deps").then((m) => m.dependencyAnalyzerTool)],
  ["network", () => import("./tools/network").then((m) => m.networkMapTool)],
  ["network_map", () => import("./tools/network").then((m) => m.networkMapTool)],
  ["sql", () => import("./tools/sql").then((m) => m.sqlAuditTool)],
  ["sql_audit", () => import("./tools/sql").then((m) => m.sqlAuditTool)],
  ["env_safety", () => import("./tools/env_safety").then((m) => m.envSafetyTool)],
  ["env_audit", () => import("./tools/env_safety").then((m) => m.envSafetyTool)],
  ["container", () => import("./tools/container").then((m) => m.containerAuditTool)],
  ["container_audit", () => import("./tools/container").then((m) => m.containerAuditTool)],
  ["flow", () => import("./tools/flow").then((m) => m.flowTraceTool)],
  ["flow_trace", () => import("./tools/flow").then((m) => m.flowTraceTool)],
  ["entropy", () => import("./tools/entropy").then((m) => m.entropyScannerTool)],
  ["entropy_scan", () => import("./tools/entropy").then((m) => m.entropyScannerTool)],
  ["auth", () => import("./tools/auth").then((m) => m.accessControlAuditTool)],
  ["auth_audit", () => import("./tools/auth").then((m) => m.accessControlAuditTool)],
  ["report", () => import("./tools/report").then((m) => m.securityReportTool)],
  ["security_report", () => import("./tools/report").then((m) => m.securityReportTool)],
  ["ast_grep", () => import("./tools/ast_grep").then((m) => m.astGrepTool)],
  ["git_forensics", () => import("./tools/git_forensics").then((m) => m.gitForensicsTool)],
  ["threat_model", () => import("./tools/threat_model").then((m) => m.threatModelTool)],
  ["auto_patch", () => import("./tools/auto_patch").then((m) => m.autoPatchTool)],
  ["fuzzer", () => import("./tools/fuzzer").then((m) => m.dynamicFuzzerTool)],
  ["cve_audit", () => import("./tools/cve_audit").then((m) => m.cveAuditTool)],
  ["mutation", () => import("./tools/mutation").then((m) => m.mutationTesterTool)],
  ["sandbox_run", () => import("./tools/sandbox_run").then((m) => m.sandboxRunnerTool)],
  ["traffic_poison", () => import("./tools/traffic_poison").then((m) => m.trafficPoisonerTool)],
  ["mock_poison", () => import("./tools/mock_poison").then((m) => m.mockPoisonerTool)],
  ["read_many", () => import("./tools/read_many").then((m) => m.readManyTool)],
  ["json_probe", () => import("./tools/json_probe").then((m) => m.jsonProbeTool)],
  ["validation_profile", () => import("./tools/validation_profile").then((m) => m.detectWorkspaceCapabilitiesTool)],
  ["validation_plan", () => import("./tools/validation_plan").then((m) => m.validationPlanTool)],
  ["validation_persistence", () => import("./tools/validation_persistence").then((m) => m.validationPersistenceTool)],
  ["run_tests", () => import("./tools/run_tests").then((m) => m.runTestsTool)],
  ["find_similar_failures", () => import("./tools/failure_memory").then((m) => m.findSimilarFailuresTool)],
  ["record_failure", () => import("./tools/failure_memory").then((m) => m.recordFailureTool)],
  ["record_resolution", () => import("./tools/failure_memory").then((m) => m.recordResolutionTool)],
  ["supermemory", () => import("./tools/supermemory").then((m) => m.supermemoryTool)],
  ["pdf_report", () => import("./tools/pdf_report").then((m) => m.pdfReportTool)],
  ["pdf_security_report", () => import("./tools/pdf_report").then((m) => m.pdfReportTool)],
  ["glob", () => import("./tools/glob").then((m) => m.globTool)],
  ["pwd", () => import("./tools/pwd").then((m) => m.pwdTool)],
  ["du", () => import("./tools/du").then((m) => m.duTool)],
  ["find", () => import("./tools/find").then((m) => m.findTool)],
  ["package_audit", () => import("./tools/package_audit").then((m) => m.packageAuditTool)],
  ["file_editor", () => import("./tools/file_editor").then((m) => m.fileEditorTool)],
  ["http_prober", () => import("./tools/http_prober").then((m) => m.httpProberTool)],
  ["redos_analyzer", () => import("./tools/redos_analyzer").then((m) => m.redosAnalyzerTool)],
  ["jwt_decoder", () => import("./tools/jwt_decoder").then((m) => m.jwtDecoderTool)],
  ["browser_prober", () => import("./tools/browser_prober").then((m) => m.browserProberTool)],
  ["source_map_analyzer", () => import("./tools/source_map_analyzer").then((m) => m.sourceMapAnalyzerTool)],
  ["oob_listener", () => import("./tools/oob_listener").then((m) => m.oobListenerTool)],
  ["creds_validator", () => import("./tools/creds_validator").then((m) => m.credsValidatorTool)],
  ["prototype_pollution_fuzzer", () => import("./tools/prototype_pollution_fuzzer").then((m) => m.prototypePollutionFuzzerTool)],
  ["local_network_recon", () => import("./tools/local_network_recon").then((m) => m.localNetworkReconTool)],
  ["repo_graph", () => import("./tools/repo_graph").then((m) => m.repoGraphTool)],
  ["security_path_trace", () => import("./tools/security_path_trace").then((m) => m.securityPathTraceTool)],
  ["attack_surface_scan", () => import("./tools/attack_surface_scan").then((m) => m.attackSurfaceScanTool)],
  ["candidate_revalidator", () => import("./tools/candidate_revalidator").then((m) => m.candidateRevalidatorTool)],
  ["evidence_pack", () => import("./tools/evidence_pack").then((m) => m.evidencePackTool)],
  ["deep_analysis_pipeline", () => import("./tools/deep_analysis_pipeline").then((m) => m.deepAnalysisPipelineTool)],
  ["semgrep_scan", () => import("./tools/semgrep_scan").then((m) => m.semgrepScanTool)],
  ["eslint_scan", () => import("./tools/eslint_scan").then((m) => m.eslintScanTool)],
];
