/**
 * Lightweight definition for tool "ast_grep".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/ast_grep.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const astGrepDefinition = {
  name: "ast_grep" as const,
  description: "Context-aware semantic grep. Finds regex matches and returns surrounding code blocks (functions, classes, declarations) with line ranges.",
  parameters: {
    type: "object",
    properties: {
      query: {
        type: "string",
        description: "The regex pattern to search for (e.g., 'eval\\\\(').",
      },
      path: {
        type: "string",
        description: "The directory or file to scan. Defaults to '.'.",
      },
      maxResults: {
        type: "number",
        description: "Max number of blocks to return. Defaults to 5, capped at 25.",
      },
      contextLines: {
        type: "number",
        description: "Fallback lines before/after each match when no code block is found. Defaults to 2, capped at 20.",
      },
      glob: {
        type: "string",
        description: "Optional ripgrep glob filter, e.g. '**/*.{ts,tsx}'.",
      },
      caseSensitive: {
        type: "boolean",
        description: "Use case-sensitive matching. Defaults to true.",
      },
    },
    required: ["query"],
  } as ToolParametersSchema,
  aliases: ["ast_grep"] as readonly string[],
};

export type AstGrepDefinition = typeof astGrepDefinition;
