/**
 * Lightweight definition for tool "attack_surface_scan".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/attack_surface_scan.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const attackSurfaceScanDefinition = {
  name: "attack_surface_scan" as const,
  description: "Runs a cheap wide-net attack surface candidate scan before expensive AI review. Classifies source role, ranks evidence, and returns a focused investigation queue.",
  parameters: {
    type: 'object',
    properties: {
      path: {
        type: 'string',
        description: 'Directory or file to scan relative to workspace root. Defaults to ".".',
      },
      limit: {
        type: 'number',
        description: 'Maximum evidence rows to return. Defaults to 80.',
      },
    },
    required: [],
  } as ToolParametersSchema,
  aliases: ["attack_surface_scan"] as readonly string[],
};

export type AttackSurfaceScanDefinition = typeof attackSurfaceScanDefinition;
