/**
 * Lightweight definition for tool "auth_audit".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/auth.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const authAuditDefinition = {
  name: "auth_audit" as const,
  description: "Analyzes application routes and identifies potentially unprotected or inconsistent access control patterns.",
  parameters: {
    type: 'object',
    properties: {
      path: {
        type: 'string',
        description: 'The directory to scan for routes (e.g., "src/routes"). Defaults to ".".',
      },
    },
    required: [],
  } as ToolParametersSchema,
  aliases: ["auth","auth_audit"] as readonly string[],
};

export type AuthAuditDefinition = typeof authAuditDefinition;
