/**
 * Lightweight definition for tool "auto_patch".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/auto_patch.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const autoPatchDefinition = {
  name: "auto_patch" as const,
  description: "An Active Remediation tool that replaces a vulnerable block of code with a secure patch and returns PATCH_IMPACT_SUMMARY_JSON. Does not create backup files.",
  parameters: {
    type: "object",
    properties: {
      path: {
        type: "string",
        description: "The file to patch (relative to workspace).",
      },
      searchString: {
        type: "string",
        description: "The exact vulnerable string/block to replace. Must exactly match the file.",
      },
      replacementString: {
        type: "string",
        description: "The secure code to inject.",
      },
      replaceAll: {
        type: "boolean",
        description:
          "Replace every occurrence when true. Defaults to false (single replacement).",
      },
      allowHighImpact: {
        type: "boolean",
        description:
          "Set true only after explicit user confirmation when PATCH_IMPACT_DECISION requires confirmation.",
      },
    },
    required: ["path", "searchString", "replacementString"],
  } as ToolParametersSchema,
  aliases: ["auto_patch"] as readonly string[],
};

export type AutoPatchDefinition = typeof autoPatchDefinition;
