/**
 * Lightweight definition for tool "browser_prober".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/browser_prober.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const browserProberDefinition = {
  name: "browser_prober" as const,
  description: "Headless Electron browser that loads a URL in an isolated, ephemeral session and returns a structured probe report. Captures: HTTP status + response headers, outbound request log, cookies, browser console output, optional DOM script result, and optional screenshot. Ideal for DOM XSS testing, CSP inspection, cookie security audits, tracking pixel detection, and dynamic frontend security analysis. All probes run in a sandboxed offscreen window with no shared state between runs.",
  parameters: {
    type: "object",
    properties: {
      url: {
        type: "string",
        description: "The fully-qualified URL to navigate to (http/https).",
      },
      script: {
        type: "string",
        description:
          "Optional JavaScript to execute in the page after it loads. " +
          "Must return a value (string, object, or array). " +
          "If omitted, only metadata is collected.",
      },
      wait_for: {
        type: "string",
        enum: ["load", "domcontentloaded", "networkidle"],
        description:
          '"load" — waits for the window load event (default). ' +
          '"domcontentloaded" — faster, stops at DOMContentLoaded. ' +
          '"networkidle" — waits until ≤2 in-flight requests remain.',
      },
      timeout_ms: {
        type: "number",
        description:
          "Hard timeout in milliseconds. Default: 15000. Max: 60000.",
      },
      capture_screenshot: {
        type: "boolean",
        description:
          "If true, captures a PNG screenshot and returns it as a base64 string.",
      },
      intercept_requests: {
        type: "boolean",
        description:
          "If true, records all outbound network requests (URL, method, resource type) made during the probe.",
      },
      extract_cookies: {
        type: "boolean",
        description:
          "If true, extracts all cookies visible to the page after load.",
      },
    },
    required: ["url"],
  } as ToolParametersSchema,
  aliases: ["browser_prober"] as readonly string[],
};

export type BrowserProberDefinition = typeof browserProberDefinition;
