/**
 * Lightweight definition for tool "candidate_revalidator".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/candidate_revalidator.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const candidateRevalidatorDefinition = {
  name: "candidate_revalidator" as const,
  description: "Revalidates one attack_surface_scan candidate with local file context. Separates confirmed candidates, likely false positives, and items needing deeper source-to-sink tracing.",
  parameters: {
    type: 'object',
    properties: {
      file: {
        type: 'string',
        description: 'Candidate file path relative to workspace root.',
      },
      line: {
        type: 'number',
        description: 'Candidate line number from attack_surface_scan.',
      },
      title: {
        type: 'string',
        description: 'Candidate title or matcher type.',
      },
      evidence: {
        type: 'string',
        description: 'Original candidate evidence line.',
      },
      contextRadius: {
        type: 'number',
        description: 'Lines before and after candidate to inspect. Defaults to 18.',
      },
    },
    required: ['file', 'line'],
  } as ToolParametersSchema,
  aliases: ["candidate_revalidator"] as readonly string[],
};

export type CandidateRevalidatorDefinition = typeof candidateRevalidatorDefinition;
