/**
 * Lightweight definition for tool "container_audit".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/container.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const containerAuditDefinition = {
  name: "container_audit" as const,
  description: "Audits Docker, Docker Compose, and Kubernetes configs for common container security misconfigurations with line evidence and remediation.",
  parameters: {
    type: 'object',
    properties: {
      path: {
        type: 'string',
        description: 'The directory to scan for container configs. Defaults to ".".',
      },
      maxFindings: {
        type: 'number',
        description: 'Max findings to return. Defaults to 50, capped at 200.',
      },
    },
    required: [],
  } as ToolParametersSchema,
  aliases: ["container","container_audit"] as readonly string[],
};

export type ContainerAuditDefinition = typeof containerAuditDefinition;
