/**
 * Lightweight definition for tool "creds_validator".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/creds_validator.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const credsValidatorDefinition = {
  name: "creds_validator" as const,
  description: "Actively validates leaked secrets/tokens against provider APIs (GitHub, AWS, etc) to confirm critical impact.",
  parameters: {
    type: 'object',
    properties: {
      provider: {
        type: 'string',
        description: 'The service provider (e.g., "github", "npm", "slack").',
      },
      token: {
        type: 'string',
        description: 'The raw secret or token to validate.',
      },
    },
    required: ['provider', 'token'],
  } as ToolParametersSchema,
  aliases: ["creds_validator"] as readonly string[],
};

export type CredsValidatorDefinition = typeof credsValidatorDefinition;
