/**
 * Lightweight definition for tool "cve_audit".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/cve_audit.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const cveAuditDefinition = {
  name: "cve_audit" as const,
  description: "Audits dependency CVEs across Bun, npm, pnpm, and Yarn projects. Detects lockfiles, runs available package manager audits, and returns normalized severity/fix summaries.",
  parameters: {
    type: "object",
    properties: {
      packageManager: {
        type: "string",
        enum: ["auto", "bun", "npm", "pnpm", "yarn"],
        description: "Package manager to use. Defaults to auto-detect from lockfiles.",
      },
      path: {
        type: "string",
        description: "Workspace-relative package directory to audit. Defaults to '.'.",
      },
      limit: {
        type: "number",
        description: "Max normalized findings per package manager. Defaults to 25, capped at 100.",
      },
      timeoutMs: {
        type: "number",
        description: "Per-audit timeout in milliseconds. Defaults to 60000, capped at 180000.",
      },
    },
    required: [],
  } as ToolParametersSchema,
  aliases: ["cve_audit"] as readonly string[],
};

export type CveAuditDefinition = typeof cveAuditDefinition;
