/**
 * Lightweight definition for tool "deep_analysis_pipeline".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/deep_analysis_pipeline.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const deepAnalysisPipelineDefinition = {
  name: "deep_analysis_pipeline" as const,
  description: "Runs the MaTE X Deep Analysis Pipeline: cheap candidate scan, additive FileRecord persistence, heuristic revalidation, triage, and Git ownership enrichment. Use before expensive agent review.",
  parameters: {
    type: 'object',
    properties: {
      path: {
        type: 'string',
        description: 'Directory or file to analyze relative to workspace root. Defaults to "src".',
      },
      limit: {
        type: 'number',
        description: 'Maximum candidates to revalidate and report. Defaults to 40.',
      },
      dataDir: {
        type: 'string',
        description: 'Workspace-relative directory for additive FileRecord JSON. Defaults to ".mate-x/deep-analysis".',
      },
    },
    required: [],
  } as ToolParametersSchema,
  aliases: ["deep_analysis_pipeline"] as readonly string[],
};

export type DeepAnalysisPipelineDefinition = typeof deepAnalysisPipelineDefinition;
