/**
 * Lightweight definition for tool "dependency_check".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/deps.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const dependencyCheckDefinition = {
  name: "dependency_check" as const,
  description: "Analyzes manifest files (package.json, requirements.txt, pyproject.toml, Cargo.toml, go.mod) for supply-chain risks: suspicious lifecycle scripts, insecure protocols, unpinned versions, install hooks, and git/file dependency substitutions.",
  parameters: {
    type: 'object',
    properties: {
      path: {
        type: 'string',
        description:
          'Path to the manifest file relative to workspace root. ' +
          'Defaults to "package.json". ' +
          'Supports: package.json, requirements.txt, pyproject.toml, Cargo.toml, go.mod.',
      },
      include_info: {
        type: 'boolean',
        description: 'If true, include informational findings (stack detection, pinned deps). Defaults to false.',
      },
    },
    required: [],
  } as ToolParametersSchema,
  aliases: ["deps","dependency_check"] as readonly string[],
};

export type DependencyCheckDefinition = typeof dependencyCheckDefinition;
