/**
 * Lightweight definition for tool "detect_workspace_capabilities".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/validation_profile.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const detectWorkspaceCapabilitiesDefinition = {
  name: "detect_workspace_capabilities" as const,
  description: "Detects the capabilities of the workspace, inferring package manager, test frameworks, and correct validation commands based on files like package.json, pytest.ini, etc.",
  parameters: {
    type: "object",
    properties: {},
  } as ToolParametersSchema,
  aliases: ["validation_profile"] as readonly string[],
};

export type DetectWorkspaceCapabilitiesDefinition = typeof detectWorkspaceCapabilitiesDefinition;
