/**
 * Lightweight definition for tool "du".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/du.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const duDefinition = {
  name: "du" as const,
  description: "Estimate file space usage of a directory or file. Supports depth-limited breakdowns and top-N largest entry reports.",
  parameters: {
    type: 'object',
    properties: {
      path: {
        type: 'string',
        description: 'Path to check (relative to workspace root). Defaults to ".".',
      },
      depth: {
        type: 'number',
        description:
          'How many directory levels to show in the breakdown (0 = total only, 1 = immediate children, …). Defaults to 1.',
      },
      top: {
        type: 'number',
        description:
          'If set, return only the N largest entries instead of a full tree. Overrides depth.',
      },
    },
  } as ToolParametersSchema,
  aliases: ["du"] as readonly string[],
};

export type DuDefinition = typeof duDefinition;
