/**
 * Lightweight definition for tool "entropy_scan".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/entropy.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const entropyScanDefinition = {
  name: "entropy_scan" as const,
  description: "Calculates Shannon entropy to identify unusually random strings that might be hardcoded secrets or tokens.",
  parameters: {
    type: 'object',
    properties: {
      path: {
        type: 'string',
        description: 'The directory or file to scan (relative to workspace root). Defaults to ".".',
      },
      threshold: {
        type: 'number',
        description: 'Entropy threshold (0-8). Higher means more random. Defaults to 4.5.',
      },
    },
    required: [],
  } as ToolParametersSchema,
  aliases: ["entropy","entropy_scan"] as readonly string[],
};

export type EntropyScanDefinition = typeof entropyScanDefinition;
