/**
 * Lightweight definition for tool "env_audit".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/env_safety.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const envAuditDefinition = {
  name: "env_audit" as const,
  description: "Audits environment management, checking .gitignore compliance and identifying leaked or mismatched keys.",
  parameters: {
    type: 'object',
    properties: {
      path: {
        type: 'string',
        description: 'The directory to audit. Defaults to ".".',
      },
    },
    required: [],
  } as ToolParametersSchema,
  aliases: ["env_safety","env_audit"] as readonly string[],
};

export type EnvAuditDefinition = typeof envAuditDefinition;
