/**
 * Lightweight definition for tool "eslint_scan".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/eslint_scan.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const eslintScanDefinition = {
  name: "eslint_scan" as const,
  description: "High-performance local ESLint scanner. Audits code quality and security rule compliance, with an optional auto-fix flag to automatically repair simple issues.",
  parameters: {
    type: "object",
    properties: {
      path: {
        type: "string",
        description: "The file or directory to scan (default: '.').",
      },
      fix: {
        type: "boolean",
        description: "Automatically fix simple formatting and security violations.",
      },
      ext: {
        type: "string",
        description: "Comma-separated list of file extensions to scan (default: '.js,.ts,.jsx,.tsx').",
      },
    },
    required: [],
  } as ToolParametersSchema,
  aliases: ["eslint_scan"] as readonly string[],
};

export type EslintScanDefinition = typeof eslintScanDefinition;
