/**
 * Lightweight definition for tool "evidence_pack".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/evidence_pack.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const evidencePackDefinition = {
  name: "evidence_pack" as const,
  description: "Builds a strict security evidence pack from candidate scan, revalidation, and trace output. Enforces candidate vs finding wording.",
  parameters: {
    type: 'object',
    properties: {
      candidateSummary: {
        type: 'string',
        description: 'Relevant attack_surface_scan candidate text.',
      },
      revalidation: {
        type: 'string',
        description: 'candidate_revalidator output for this candidate.',
      },
      trace: {
        type: 'string',
        description: 'security_path_trace output for this candidate or scope.',
      },
      recommendation: {
        type: 'string',
        description: 'Optional fix or next action.',
      },
    },
    required: ['candidateSummary'],
  } as ToolParametersSchema,
  aliases: ["evidence_pack"] as readonly string[],
};

export type EvidencePackDefinition = typeof evidencePackDefinition;
