/**
 * Lightweight definition for tool "file_metadata".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/metadata.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const fileMetadataDefinition = {
  name: "file_metadata" as const,
  description: "Get detailed metadata about a file, including size, permissions, and timestamps.",
  parameters: {
    type: 'object',
    properties: {
      path: {
        type: 'string',
        description: 'The file path to inspect (relative to workspace root).',
      },
    },
    required: ['path'],
  } as ToolParametersSchema,
  aliases: ["metadata","file_metadata"] as readonly string[],
};

export type FileMetadataDefinition = typeof fileMetadataDefinition;
