/**
 * Lightweight definition for tool "file_editor".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/file_editor.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const fileEditorDefinition = {
  name: "file_editor" as const,
  description: "Precise workspace file editor for creating files, overwriting files, replacing line ranges, inserting before/after lines, deleting line ranges, and replacing exact blocks. Returns PATCH_IMPACT_SUMMARY_JSON when requested and does not create backup files.",
  parameters: {
    type: "object",
    properties: {
      path: {
        type: "string",
        description: "The file to edit (relative to workspace).",
      },
      operation: {
        type: "string",
        enum: ["replace_range", "insert_before", "insert_after", "delete_range", "replace_block", "append", "create", "overwrite"],
        description:
          "Edit operation. Defaults to replace_range for backward compatibility.",
      },
      startLine: {
        type: "number",
        description:
          "The starting line number for range operations (1-indexed, inclusive).",
      },
      endLine: {
        type: "number",
        description:
          "The ending line number for replace/delete range operations (1-indexed, inclusive).",
      },
      newContent: {
        type: "string",
        description:
          "Content to write, insert, append, or use as replacement. Optional only for delete_range.",
      },
      searchString: {
        type: "string",
        description:
          "Exact block to replace when operation is replace_block. Must match file content exactly.",
      },
      replaceAll: {
        type: "boolean",
        description:
          "For replace_block, replace all occurrences when true. Defaults to false.",
      },
      expectedContent: {
        type: "string",
        description:
          "Optional exact current content guard. For range operations it must match the target range. For append/overwrite it must match the whole file.",
      },
      failIfExists: {
        type: "boolean",
        description:
          "For create, reject if the target file already exists. Defaults to true.",
      },
      allowHighImpact: {
        type: "boolean",
        description:
          "Set true only after explicit user confirmation when PATCH_IMPACT_DECISION requires confirmation.",
      },
      impactAnalysis: {
        type: "string",
        enum: ["none", "before", "full"],
        description:
          "RepoGraph impact analysis level. Defaults to none for fast, precise edits on new or large files. Use full when dependency/risk summary is required.",
      },
    },
    required: ["path"],
  } as ToolParametersSchema,
  aliases: ["file_editor"] as readonly string[],
};

export type FileEditorDefinition = typeof fileEditorDefinition;
