/**
 * Lightweight definition for tool "find".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/find.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const findDefinition = {
  name: "find" as const,
  description: "Search files by name in workspace using pure Node. Supports exact/substr match, extension filters, excludes, hidden toggle, depth, and caps.",
  parameters: {
    type: 'object',
    properties: {
      path: {
        type: 'string',
        description: 'The directory to search in (relative to workspace root). Defaults to ".".',
      },
      name: {
        type: 'string',
        description: 'The substring to match in the filename (case-insensitive).',
      },
      exact: {
        type: 'boolean',
        description: 'Match the full filename instead of substring. Defaults to false.',
      },
      extensions: {
        type: 'array',
        items: { type: 'string' },
        description: 'Optional extension filter without dots, e.g. ["ts", "tsx"].',
      },
      exclude: {
        type: 'array',
        items: { type: 'string' },
        description: 'Optional path substrings to exclude.',
      },
      includeHidden: {
        type: 'boolean',
        description: 'Include hidden files/directories. Defaults to false.',
      },
      maxDepth: {
        type: 'number',
        description: 'Maximum directory depth to search. Defaults to 20.',
      },
      limit: {
        type: 'number',
        description: 'Max results to return. Defaults to 500, capped at 2000.',
      },
    },
    required: ['name'],
  } as ToolParametersSchema,
  aliases: ["find"] as readonly string[],
};

export type FindDefinition = typeof findDefinition;
