/**
 * Lightweight definition for tool "find_similar_failures".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/failure_memory.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const findSimilarFailuresDefinition = {
  name: "find_similar_failures" as const,
  description: "Finds prior structured failures in this workspace before retrying validation, patching, or command execution. Use before rerunning a failed task to avoid repeated failed loops.",
  parameters: {
    type: 'object',
    properties: {
      command: { type: 'string', description: 'Command about to run or retry.' },
      framework: { type: 'string', description: 'Detected framework or test runner.' },
      failingTests: {
        type: 'array',
        items: { type: 'string' },
        description: 'Known failing test names or failure lines.',
      },
      errorSignature: { type: 'string', description: 'Previously computed stable error signature.' },
      output: { type: 'string', description: 'Command output, validation output, or error text to match.' },
      stackTraceExcerpt: { type: 'string', description: 'Stack trace excerpt to match.' },
      limit: { type: 'number', description: 'Maximum matches to return.' },
    },
    required: [],
  } as ToolParametersSchema,
  aliases: ["find_similar_failures"] as readonly string[],
};

export type FindSimilarFailuresDefinition = typeof findSimilarFailuresDefinition;
