/**
 * Lightweight definition for tool "flow_trace".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/flow.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const flowTraceDefinition = {
  name: "flow_trace" as const,
  description: "Heuristically traces data flow from a source term to aliases, function calls, and risky sinks across workspace files.",
  parameters: {
    type: "object",
    properties: {
      source: {
        type: "string",
        description:
          'The starting variable or parameter name to trace (e.g., "req.body.username").',
      },
      path: {
        type: "string",
        description: "Workspace-relative path to search. Defaults to '.'.",
      },
      maxDepth: {
        type: "number",
        description:
          "Maximum number of assignment steps to trace. Defaults to 5, capped at 12.",
      },
      sinks: {
        type: "array",
        items: { type: "string" },
        description: "Optional sink names/properties to flag. Defaults to common command, SQL, DOM, IPC, file, and network sinks.",
      },
      glob: {
        type: "string",
        description: "Optional ripgrep glob filter, e.g. '**/*.{ts,tsx,js}'.",
      },
      maxMatches: {
        type: "number",
        description: "Max rg matches per term. Defaults to 200, capped at 1000.",
      },
      timeoutMs: {
        type: "number",
        description: "Per-search timeout in milliseconds. Defaults to 20000, capped at 60000.",
      },
    },
    required: ["source"],
  } as ToolParametersSchema,
  aliases: ["flow","flow_trace"] as readonly string[],
};

export type FlowTraceDefinition = typeof flowTraceDefinition;
