/**
 * Lightweight definition for tool "fuzzer".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/fuzzer.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const fuzzerDefinition = {
  name: "fuzzer" as const,
  description: "A Dynamic Application Security Testing (DAST) fuzzer. Sends potentially malicious payloads to a local endpoint to dynamically verify exploibility.",
  parameters: {
    type: "object",
    properties: {
      url: {
        type: "string",
        description: "The local endpoint to hit (e.g., 'http://127.0.0.1:3000/api/search'). Must be localhost.",
      },
      method: {
        type: "string",
        description: "HTTP method (GET, POST).",
      },
      fuzzTarget: {
        type: "string",
        description: "The payload type to test: 'SQLI', 'XSS', 'CMDI'.",
      },
    },
    required: ["url", "method", "fuzzTarget"],
  } as ToolParametersSchema,
  aliases: ["fuzzer"] as readonly string[],
};

export type FuzzerDefinition = typeof fuzzerDefinition;
