/**
 * Lightweight definition for tool "git_forensics".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/git_forensics.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const gitForensicsDefinition = {
  name: "git_forensics" as const,
  description: "Analyzes git history to compute file churn and identify risk hotspots. Files that change most often are statistically the highest risk for vulnerabilities.",
  parameters: {
    type: "object",
    properties: {
      monthsOut: {
        type: "number",
        description: "Number of months of git history to analyze. Defaults to 6, capped at 36.",
      },
      limit: {
        type: "number",
        description: "Number of hotspot files to return. Defaults to 10, capped at 50.",
      },
      includeWorkingTree: {
        type: "boolean",
        description: "Include currently modified/untracked files as extra risk signal. Defaults to true.",
      },
    },
    required: [],
  } as ToolParametersSchema,
  aliases: ["git_forensics"] as readonly string[],
};

export type GitForensicsDefinition = typeof gitForensicsDefinition;
