/**
 * Lightweight definition for tool "git_diag".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/git.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const gitDiagDefinition = {
  name: "git_diag" as const,
  description: "Read-only git diagnostics for the active workspace: log (recent commits), show (commit details), and diff (working tree changes). Use for change review and vulnerability archaeology. Does not commit, push, checkout, or mutate the repository.",
  parameters: {
    type: 'object',
    properties: {
      operation: {
        type: 'string',
        enum: ['log', 'show', 'diff'],
        description: 'Git diagnostic operation to perform.',
      },
      limit: {
        type: 'number',
        description: 'For log: number of commits to show. Defaults to 5; max 50.',
        minimum: 1,
        maximum: 50,
      },
      commitHash: {
        type: 'string',
        description: 'For show: commit hash prefix to inspect (matched against recent history).',
        minLength: 4,
      },
    },
    required: ['operation'],
  } as ToolParametersSchema,
  aliases: ["git","git_diag"] as readonly string[],
};

export type GitDiagDefinition = typeof gitDiagDefinition;
