/**
 * Lightweight definition for tool "glob".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/glob.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const globDefinition = {
  name: "glob" as const,
  description: "Search for files by glob with trust-scope enforcement, excludes, type filters, hidden/ignored toggles, result caps, and summary metadata.",
  parameters: {
    type: 'object',
    properties: {
      pattern: {
        type: 'string',
        description: 'The glob pattern to search for (e.g., "**/*.ts" or "src/components/**/*.tsx").',
      },
      path: {
        type: 'string',
        description: 'Optional path or directory to restrict the search within. Defaults to the workspace root.',
      },
      exclude: {
        type: 'array',
        items: { type: 'string' },
        description: 'Optional extra glob patterns to exclude, e.g. ["**/*.test.ts", "fixtures/**"].',
      },
      extensions: {
        type: 'array',
        items: { type: 'string' },
        description: 'Optional extension filter without dots, e.g. ["ts", "tsx"].',
      },
      includeHidden: {
        type: 'boolean',
        description: 'Include hidden files and directories. Defaults to false.',
      },
      noIgnore: {
        type: 'boolean',
        description: 'Ignore .gitignore/.ignore rules. Defaults to false.',
      },
      limit: {
        type: 'number',
        description: 'Max results to return. Defaults to 500, capped at 2000.',
      },
      timeoutMs: {
        type: 'number',
        description: 'Search timeout in milliseconds. Defaults to 15000, capped at 60000.',
      },
    },
    required: ['pattern'],
  } as ToolParametersSchema,
  aliases: ["glob"] as readonly string[],
};

export type GlobDefinition = typeof globDefinition;
