/**
 * Lightweight definition for tool "http_prober".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/http_prober.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const httpProberDefinition = {
  name: "http_prober" as const,
  description: "Make an HTTP request to dynamically probe an endpoint (e.g., localhost APIs). Allows testing for XSS/SQLi dynamically.",
  parameters: {
    type: 'object',
    properties: {
      url: {
        type: 'string',
        description: 'The exact URL to probe (e.g., "http://localhost:5173/api/data"). Infer the port from the project stack.',
      },
      method: {
        type: 'string',
        description: 'HTTP method (GET, POST, PUT, DELETE). Defaults to GET.',
      },
      headers: {
        type: 'string',
        description: 'JSON string of headers to send.',
      },
      body: {
        type: 'string',
        description: 'Stringified body content for POST/PUT requests.',
      },
    },
    required: ['url'],
  } as ToolParametersSchema,
  aliases: ["http_prober"] as readonly string[],
};

export type HttpProberDefinition = typeof httpProberDefinition;
