/**
 * Lightweight definition for tool "json_probe".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/json_probe.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const jsonProbeDefinition = {
  name: "json_probe" as const,
  description: "Read and query JSON files by dot-path, returning compact structured output.",
  parameters: {
    type: "object",
    properties: {
      path: {
        type: "string",
        description: "JSON file path relative to workspace root.",
      },
      query: {
        type: "string",
        description: "Optional dot-path selector (e.g., dependencies.react).",
      },
      pretty: {
        type: "boolean",
        description: "Pretty-print output. Defaults to true.",
      },
    },
    required: ["path"],
  } as ToolParametersSchema,
  aliases: ["json_probe"] as readonly string[],
};

export type JsonProbeDefinition = typeof jsonProbeDefinition;
