/**
 * Lightweight definition for tool "jwt_decoder".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/jwt_decoder.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const jwtDecoderDefinition = {
  name: "jwt_decoder" as const,
  description: "Decode and inspect a JWT or Base64Url token. Useful for checking claims, roles, and detecting insecure algorithms like \"none\".",
  parameters: {
    type: 'object',
    properties: {
      token: {
        type: 'string',
        description: 'The raw JWT string to decode.',
      },
    },
    required: ['token'],
  } as ToolParametersSchema,
  aliases: ["jwt_decoder"] as readonly string[],
};

export type JwtDecoderDefinition = typeof jwtDecoderDefinition;
