/**
 * Lightweight definition for tool "local_network_recon".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/local_network_recon.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const localNetworkReconDefinition = {
  name: "local_network_recon" as const,
  description: "Hyper-fast TCP port scanner for localhost to discover exposed internal services (Databases, Docker, Caches).",
  parameters: {
    type: 'object',
    properties: {},
  } as ToolParametersSchema,
  aliases: ["local_network_recon"] as readonly string[],
};

export type LocalNetworkReconDefinition = typeof localNetworkReconDefinition;
