/**
 * Lightweight definition for tool "ls".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/ls.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const lsDefinition = {
  name: "ls" as const,
  description: "List directory entries in the active workspace. Use to inspect project structure before reading files. Defaults to the workspace root. Recursive listings are capped to protect performance. Does not read file contents; use read for that. Mutates nothing.",
  parameters: {
    type: 'object',
    properties: {
      path: {
        type: 'string',
        description: 'Directory path relative to the workspace root. Defaults to ".".',
      },
      recursive: {
        type: 'boolean',
        description: 'List contents recursively. Defaults to false. Caps at 4000 entries.',
      },
    },
    required: [],
  } as ToolParametersSchema,
  aliases: ["ls"] as readonly string[],
};

export type LsDefinition = typeof lsDefinition;
