/**
 * Lightweight definition for tool "mock_poison".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/mock_poison.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const mockPoisonDefinition = {
  name: "mock_poison" as const,
  description: "An External Dependency Emulator. Temporarily spins up a local mock HTTP server that intentionally serves highly malicious payloads (oversized buffers, XML bombs, malformed JSON) to see if the client application safely handles compromised third-party data.",
  parameters: {
    type: "object",
    properties: {
      action: {
        type: "string",
        description: "'start' or 'stop' the mock server, or 'status' to check hits.",
      },
      port: {
        type: "number",
        description: "The local port to bind the mock server to. Defaults to 9999.",
      },
      payloadType: {
        type: "string",
        description: "The malicious payload to serve: 'XML_BOMB', 'HUGE_BUFFER', 'MALFORMED_JSON', 'XSS_JSON'.",
      },
    },
    required: ["action"],
  } as ToolParametersSchema,
  aliases: ["mock_poison"] as readonly string[],
};

export type MockPoisonDefinition = typeof mockPoisonDefinition;
