/**
 * Lightweight definition for tool "mutation".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/mutation.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const mutationDefinition = {
  name: "mutation" as const,
  description: "Injects a temporary fault (mutation) into source code, runs a verification command to see if the system catches the invisible glitch, and automatically safely restores the original code.",
  parameters: {
    type: "object",
    properties: {
      path: {
        type: "string",
        description: "The file to mutate (relative to workspace).",
      },
      searchString: {
        type: "string",
        description: "The exact logic to mutate (e.g., 'if (req.user)').",
      },
      mutationString: {
        type: "string",
        description: "The temporary glitch to inject (e.g., 'if (!req.user)').",
      },
      verificationCommand: {
        type: "string",
        description: "The shell command to run while mutated (e.g., 'bun test' or 'curl http://...').",
      },
    },
    required: ["path", "searchString", "mutationString", "verificationCommand"],
  } as ToolParametersSchema,
  aliases: ["mutation"] as readonly string[],
};

export type MutationDefinition = typeof mutationDefinition;
