/**
 * Lightweight definition for tool "network_map".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/network.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const networkMapDefinition = {
  name: "network_map" as const,
  description: "Maps the application\\",
  parameters: {
    type: 'object',
    properties: {
      path: {
        type: 'string',
        description: 'The directory or file to scan (relative to workspace root). Defaults to ".".',
      },
    },
    required: [],
  } as ToolParametersSchema,
  aliases: ["network","network_map"] as readonly string[],
};

export type NetworkMapDefinition = typeof networkMapDefinition;
