/**
 * Lightweight definition for tool "oob_listener".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/oob_listener.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const oobListenerDefinition = {
  name: "oob_listener" as const,
  description: "Out-Of-Band Listener. Starts an ephemeral local HTTP server to catch Blind SSRF/XSS callbacks. Use action=\"start\" to open it, and action=\"check\" to read caught requests.",
  parameters: {
    type: 'object',
    properties: {
      action: {
        type: 'string',
        description: '"start" to launch the listener. "check" to retrieve caught requests and stop the server.',
      },
    },
    required: ['action'],
  } as ToolParametersSchema,
  aliases: ["oob_listener"] as readonly string[],
};

export type OobListenerDefinition = typeof oobListenerDefinition;
