/**
 * Lightweight definition for tool "package_audit".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/package_audit.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const packageAuditDefinition = {
  name: "package_audit" as const,
  description: "Run the package manager security audit to find CVEs in dependencies. Uses npm audit under the hood.",
  parameters: {
    type: 'object',
    properties: {},
  } as ToolParametersSchema,
  aliases: ["package_audit"] as readonly string[],
};

export type PackageAuditDefinition = typeof packageAuditDefinition;
