/**
 * Lightweight definition for tool "pdf_security_report".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/pdf_report.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const pdfSecurityReportDefinition = {
  name: "pdf_security_report" as const,
  description: "Generates a premium, shareable PDF security report summarizing identified risks in the workspace.",
  parameters: {
    type: 'object',
    properties: {
      scope: {
        type: 'string',
        description: 'The directory to audit. Defaults to ".".',
      },
      outputPath: {
        type: 'string',
        description: 'The filename or relative path to save the PDF. Defaults to "security-report.pdf".',
      },
    },
    required: [],
  } as ToolParametersSchema,
  aliases: ["pdf_report","pdf_security_report"] as readonly string[],
};

export type PdfSecurityReportDefinition = typeof pdfSecurityReportDefinition;
