/**
 * Lightweight definition for tool "plan_validation".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/validation_plan.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const planValidationDefinition = {
  name: "plan_validation" as const,
  description: "Creates and persists the smallest useful validation plan for a task using changed files, RepoGraph impact, package scripts, detected framework, and previous failures. This tool only plans; it never executes validation. Use run_tests and verify_validation_persistence before claiming proof.",
  parameters: {
    type: "object",
    properties: {
      objective: {
        type: "string",
        description: "The task objective or bug/fix being validated.",
      },
      changedFiles: {
        type: "array",
        items: { type: "string" },
        description: "Files changed by the current task.",
      },
      impactedFiles: {
        type: "array",
        items: { type: "string" },
        description: "Files returned by RepoGraph impact analysis.",
      },
      packageScripts: {
        type: "object",
        additionalProperties: { type: "string" },
        description: "Package scripts, keyed by script name.",
      },
      detectedFramework: {
        type: "string",
        description: "Detected framework or test runner.",
      },
    },
    required: ["objective"],
  } as ToolParametersSchema,
  aliases: ["validation_plan"] as readonly string[],
};

export type PlanValidationDefinition = typeof planValidationDefinition;
