/**
 * Lightweight definition for tool "prototype_pollution_fuzzer".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/prototype_pollution_fuzzer.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const prototypePollutionFuzzerDefinition = {
  name: "prototype_pollution_fuzzer" as const,
  description: "Tests a JS snippet or merge function for Prototype Pollution vulnerabilities inside a secure VM sandbox.",
  parameters: {
    type: 'object',
    properties: {
      code: {
        type: 'string',
        description: 'The JS code containing the merge/clone function to test. Assume it receives (target, source).',
      },
      functionName: {
        type: 'string',
        description: 'The name of the function to invoke in the code snippet.',
      },
    },
    required: ['code', 'functionName'],
  } as ToolParametersSchema,
  aliases: ["prototype_pollution_fuzzer"] as readonly string[],
};

export type PrototypePollutionFuzzerDefinition = typeof prototypePollutionFuzzerDefinition;
