/**
 * Lightweight definition for tool "pwd".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/pwd.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const pwdDefinition = {
  name: "pwd" as const,
  description: "Return the active workspace root, name, platform, and optional trust-scope paths. Use when you need the current workspace context before path-based tools. Mutates nothing.",
  parameters: {
    type: 'object',
    properties: {
      includeTrustScope: {
        type: 'boolean',
        description: 'Include allowed/forbidden workspace paths from the active trust contract. Defaults to true.',
      },
      relativeTo: {
        type: 'string',
        description: 'Optional absolute or workspace-relative path to express as relative to the workspace root.',
      },
    },
  } as ToolParametersSchema,
  aliases: ["pwd"] as readonly string[],
};

export type PwdDefinition = typeof pwdDefinition;
