/**
 * Lightweight definition for tool "read".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/read.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const readDefinition = {
  name: "read" as const,
  description: "Read a file in the active workspace. Use for inspecting source after locating paths with rg/glob/ls. Supports optional 1-indexed line ranges. Does not search or list directories. Mutates nothing.",
  parameters: {
    type: 'object',
    properties: {
      path: {
        type: 'string',
        description: 'File path relative to the workspace root.',
        minLength: 1,
      },
      lineStart: {
        type: 'number',
        description: 'Optional starting line number (1-indexed, inclusive).',
        minimum: 1,
      },
      lineEnd: {
        type: 'number',
        description: 'Optional ending line number (1-indexed, inclusive).',
        minimum: 1,
      },
    },
    required: ['path'],
  } as ToolParametersSchema,
  aliases: ["read"] as readonly string[],
};

export type ReadDefinition = typeof readDefinition;
