/**
 * Lightweight definition for tool "read_many".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/read_many.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const readManyDefinition = {
  name: "read_many" as const,
  description: "Read multiple files in one call with optional line ranges to reduce tool round-trips.",
  parameters: {
    type: "object",
    properties: {
      paths: {
        type: "array",
        items: { type: "string" },
        description: "List of file paths relative to workspace root.",
      },
      lineStart: {
        type: "number",
        description: "Optional start line (1-indexed, inclusive) applied to each file.",
      },
      lineEnd: {
        type: "number",
        description: "Optional end line (1-indexed, inclusive) applied to each file.",
      },
      maxCharsPerFile: {
        type: "number",
        description: "Optional output cap per file in characters. Defaults to 12000.",
      },
    },
    required: ["paths"],
  } as ToolParametersSchema,
  aliases: ["read_many"] as readonly string[],
};

export type ReadManyDefinition = typeof readManyDefinition;
