/**
 * Lightweight definition for tool "record_failure".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/failure_memory.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const recordFailureDefinition = {
  name: "record_failure" as const,
  description: "Records structured failure knowledge for this workspace after validation, patch attempts, or command outputs fail.",
  parameters: {
    type: 'object',
    properties: {
      command: { type: 'string', description: 'Failed command or attempted action.' },
      exitCode: { type: 'number', description: 'Process exit code if available.' },
      framework: { type: 'string', description: 'Detected framework or test runner.' },
      failingTests: {
        type: 'array',
        items: { type: 'string' },
        description: 'Failing test names or failure lines.',
      },
      errorSignature: { type: 'string', description: 'Stable normalized signature if already computed.' },
      output: { type: 'string', description: 'Command output or error text.' },
      stackTraceExcerpt: { type: 'string', description: 'Stack trace excerpt.' },
      affectedFiles: {
        type: 'array',
        items: { type: 'string' },
        description: 'Files implicated by the failure.',
      },
      attemptedFix: { type: 'string', description: 'Patch or remediation attempted before this failure.' },
      retryFixed: { type: 'boolean', description: 'Whether retry fixed the failure.' },
    },
    required: ['command'],
  } as ToolParametersSchema,
  aliases: ["record_failure"] as readonly string[],
};

export type RecordFailureDefinition = typeof recordFailureDefinition;
