/**
 * Lightweight definition for tool "record_resolution".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/failure_memory.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const recordResolutionDefinition = {
  name: "record_resolution" as const,
  description: "Marks a known failure as resolved and stores whether retry fixed it. Use after a validation retry or patch clears a known failure.",
  parameters: {
    type: 'object',
    properties: {
      failureId: { type: 'string', description: 'Failure memory ID.' },
      errorSignature: { type: 'string', description: 'Stable failure signature when ID is unavailable.' },
      command: { type: 'string', description: 'Command associated with the resolved failure.' },
      attemptedFix: { type: 'string', description: 'Fix that resolved or failed to resolve the issue.' },
      retryFixed: { type: 'boolean', description: 'Whether retry fixed this failure.' },
    },
    required: ['retryFixed'],
  } as ToolParametersSchema,
  aliases: ["record_resolution"] as readonly string[],
};

export type RecordResolutionDefinition = typeof recordResolutionDefinition;
