/**
 * Lightweight definition for tool "redos_analyzer".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/redos_analyzer.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const redosAnalyzerDefinition = {
  name: "redos_analyzer" as const,
  description: "Evaluate regex ReDoS risk using static heuristics plus timed isolated worker execution against supplied or generated attack strings.",
  parameters: {
    type: 'object',
    properties: {
      regex: {
        type: 'string',
        description: 'The raw regex string to test (without slashes). E.g. "([a-zA-Z]+)*$"',
      },
      testString: {
        type: 'string',
        description: 'Optional evil string to test. If omitted, analyzer generates adversarial inputs.',
      },
      flags: {
        type: 'string',
        description: 'Optional regex flags, e.g. "i", "m", "u".',
      },
      timeoutMs: {
        type: 'number',
        description: 'Timeout per worker execution. Defaults to 2000, capped at 10000.',
      },
      samples: {
        type: 'number',
        description: 'Number of generated attack strings to test. Defaults to 3, capped at 10.',
      },
      maxInputLength: {
        type: 'number',
        description: 'Max test string length. Defaults to 20000, capped at 100000.',
      },
    },
    required: ['regex'],
  } as ToolParametersSchema,
  aliases: ["redos_analyzer"] as readonly string[],
};

export type RedosAnalyzerDefinition = typeof redosAnalyzerDefinition;
