/**
 * Lightweight definition for tool "repo_graph".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/repo_graph.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const repoGraphDefinition = {
  name: "repo_graph" as const,
  description: "Query persistent repository semantic memory before reading files. Use semantic_search for concepts/symbols/risk surfaces, get_semantic_profile for one candidate file, get_architecture_summary for unfamiliar repos, detect_changes before refresh, and graph operations for entrypoints, impacted files, tests, imports, IPC, env vars, and dependencies.",
  parameters: {
    type: "object",
    properties: {
      operation: {
        type: "string",
        enum: [
          "refresh",
          "get_entrypoints",
          "get_impacted_files",
          "get_tests_for_file",
          "get_import_chain",
          "get_ipc_surface",
          "get_env_usage",
          "get_dependency_surface",
          "semantic_search",
          "get_semantic_profile",
          "get_architecture_summary",
          "detect_changes",
        ],
      },
      query: {
        type: "string",
        description: "Concept, symbol, behavior, risk, route, IPC, env, dependency, or feature query for semantic_search.",
      },
      limit: {
        type: "number",
        description: "Maximum semantic_search results.",
      },
      role: {
        type: "string",
        description: "Optional semantic role filter for semantic_search, such as service, agent-tool, ipc-handler, ui, contract, config, test, or runtime-code.",
      },
      risk: {
        type: "string",
        description: "Optional risk tag filter for semantic_search, such as ipc, filesystem, network, shell-exec, secrets-config, credential-flow, or security-analysis.",
      },
      files: {
        type: "array",
        items: { type: "string" },
        description: "Changed files for get_impacted_files or detect_changes.",
      },
      file: {
        type: "string",
        description: "Source file for get_tests_for_file.",
      },
      from: {
        type: "string",
        description: "Start file for get_import_chain.",
      },
      to: {
        type: "string",
        description: "Target file for get_import_chain.",
      },
      variable: {
        type: "string",
        description: "Optional env var name for get_env_usage.",
      },
    },
    required: ["operation"],
  } as ToolParametersSchema,
  aliases: ["repo_graph"] as readonly string[],
};

export type RepoGraphDefinition = typeof repoGraphDefinition;
