/**
 * Lightweight definition for tool "rg".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/rg.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const rgDefinition = {
  name: "rg" as const,
  description: "High-performance code search via ripgrep. Use for symbol, text, and regex discovery before read. Defaults skip node_modules/dist/out/build artifacts and cap noisy results. Does not edit files. Prefer path/include filters to keep results actionable.",
  parameters: {
    type: 'object',
    properties: {
      query: {
        type: 'string',
        description: 'The search term or regex pattern.',
        minLength: 1,
      },
      isRegex: {
        type: 'boolean',
        description: 'Whether to treat the query as a regular expression. Defaults to false.',
      },
      caseSensitive: {
        type: 'boolean',
        description: 'Whether the search should be case sensitive. Defaults to false.',
      },
      include: {
        type: 'string',
        description: 'Glob pattern for files to include (e.g., "*.ts").',
      },
      exclude: {
        type: 'string',
        description: 'Glob pattern for files to exclude.',
      },
      wholeWord: {
        type: 'boolean',
        description: 'Whether to match whole words only.',
      },
      path: {
        type: 'string',
        description: 'Optional file or directory path to search within. Defaults to the workspace root.',
      },
      paths: {
        type: 'array',
        items: { type: 'string' },
        description: 'Optional file or directory paths to search within. Overrides path when provided.',
      },
      contextLines: {
        type: 'number',
        description: 'Optional matching context lines before and after each match. Defaults to 0; max 8.',
      },
      maxResults: {
        type: 'number',
        description: 'Maximum result lines returned. Defaults to 80; max 500.',
      },
      maxOutputChars: {
        type: 'number',
        description: 'Maximum output characters returned. Defaults to 24000; max 120000.',
      },
      maxFilesize: {
        type: 'string',
        description: 'Skip files larger than this ripgrep size (examples: 512K, 2M, 1G). Defaults to 2M.',
      },
      hidden: {
        type: 'boolean',
        description: 'Search hidden files and directories. Defaults to false.',
      },
      sort: {
        type: 'string',
        enum: ['none', 'path'],
        description: 'Optional deterministic sorting. Use path for stable review output; none is fastest.',
      },
    },
    required: ['query'],
  } as ToolParametersSchema,
  aliases: ["rg"] as readonly string[],
};

export type RgDefinition = typeof rgDefinition;
