/**
 * Lightweight definition for tool "run_tests".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/run_tests.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const runTestsDefinition = {
  name: "run_tests" as const,
  description: "Runs tests in the workspace based on the resolved validation profile. It streams output to the UI and returns a structured JSON summary. Supported scopes: changed-files, specific path, full-suite, rerun-failed.",
  parameters: {
    type: "object",
    properties: {
      scope: {
        type: "string",
        enum: ["full-suite", "changed-files", "rerun-failed", "specific-path"],
        description: "The scope of the tests to run."
      },
      specificPath: {
        type: "string",
        description: "The specific file or directory to test, if scope is specific-path."
      },
      plannedCommand: {
        type: "string",
        enum: ["primary", "fallback"],
        description: "When a validation plan exists, choose the primary or fallback command from that plan."
      }
    },
    required: ["scope"],
  } as ToolParametersSchema,
  aliases: ["run_tests"] as readonly string[],
};

export type RunTestsDefinition = typeof runTestsDefinition;
