/**
 * Lightweight definition for tool "sandbox_run".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/sandbox_run.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const sandboxRunDefinition = {
  name: "sandbox_run" as const,
  description: "Runs a configurable, time-bounded child process for validation or diagnostics. Defaults to executionMode isolated-copy, which runs in a temporary workspace copy and removes it afterward. executionMode direct runs in the real workspace and requires policy approval because file writes, package-manager mutations, lockfile updates, and generated artifacts can affect the real project.",
  parameters: {
    type: "object",
    properties: {
      command: {
        type: "string",
        description: "Direct executable command, optionally with simple whitespace-separated args. Shell operators are rejected. Prefer command plus args for precision.",
      },
      args: {
        type: "array",
        items: { type: "string" },
        description:
          "Optional explicit argv list. When provided, command must be only the executable name or path, e.g. command 'bun', args ['run', 'typecheck'].",
      },
      timeoutSeconds: {
        type: "number",
        enum: [30, 45, 60, 120, 240],
        description:
          "Process timeout. Use 30 for quick checks, 45/60 for normal tests, 120/240 for slow builds or integration checks that would otherwise freeze or be killed early.",
      },
      maxOutputChars: {
        type: "number",
        enum: [1000, 4000, 8000, 16000],
        description:
          "Maximum combined stdout/stderr characters captured in the report.",
      },
      port: {
        type: "number",
        description:
          "PORT value for commands that start local servers. Must be 1024-65535. Defaults to 4000.",
      },
      nodeEnv: {
        type: "string",
        enum: ["test", "development", "production"],
        description:
          "NODE_ENV for the child process. Defaults to test for validation isolation.",
      },
      keepAwake: {
        type: "boolean",
        description:
          "Use Electron powerSaveBlocker during the run. Defaults to false for power efficiency. Set true only for interactive/browser runs or long validations that must not be suspended.",
      },
      powerSaveBlockerType: {
        type: "string",
        enum: ["prevent-app-suspension", "prevent-display-sleep"],
        description:
          "Electron powerSaveBlocker mode when keepAwake is active. Use prevent-app-suspension for normal long tests; prevent-display-sleep for interactive/browser scenarios that must keep the display awake.",
      },
      executionMode: {
        type: "string",
        enum: ["direct", "isolated-copy"],
        description:
          "Workspace execution mode. direct runs in the real workspace. isolated-copy runs in a temporary copy that excludes node_modules, .git, build outputs, logs, maps, and coverage, then removes it after the run.",
      },
    },
    required: ["command"],
  } as ToolParametersSchema,
  aliases: ["sandbox_run"] as readonly string[],
};

export type SandboxRunDefinition = typeof sandboxRunDefinition;
