/**
 * Lightweight definition for tool "secret_scan".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/secrets.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const secretScanDefinition = {
  name: "secret_scan" as const,
  description: "Scans workspace files for hardcoded secrets with redacted evidence, severity, entropy checks, path guards, and result caps.",
  parameters: {
    type: "object",
    properties: {
      path: {
        type: "string",
        description:
          'The directory or file to scan (relative to workspace root). Defaults to ".".',
      },
      limit: {
        type: "number",
        description: "Max findings to return. Defaults to 100, capped at 500.",
      },
      includeGenerated: {
        type: "boolean",
        description: "Include generated/build outputs normally skipped. Defaults to false.",
      },
      maxFileBytes: {
        type: "number",
        description: "Max file size to read. Defaults to 1MB, capped at 5MB.",
      },
      useOnnx: {
        type: "boolean",
        description: "Use optional MaTE X Privacy model for semantic secret detection. Defaults to true.",
      },
      mlBackend: {
        type: "string",
        enum: ["transformers", "onnx", "off"],
        description: "ML backend for optional semantic scan. Defaults to transformers; falls back gracefully.",
      },
      onnxMinConfidence: {
        type: "number",
        description: "Minimum ML span confidence. Defaults to 0.72.",
      },
      onnxMaxFiles: {
        type: "number",
        description: "Max files to scan with ONNX after regex checks. Defaults to 50, capped at 300.",
      },
    },
    required: [],
  } as ToolParametersSchema,
  aliases: ["secrets","secret_scan"] as readonly string[],
};

export type SecretScanDefinition = typeof secretScanDefinition;
