/**
 * Lightweight definition for tool "security_report".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/report.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const securityReportDefinition = {
  name: "security_report" as const,
  description: "Generates a comprehensive, prioritized security posture report by aggregating findings from multiple diagnostic tools.",
  parameters: {
    type: 'object',
    properties: {
      scope: {
        type: 'string',
        description: 'The directory to audit. Defaults to ".".',
      },
    },
    required: [],
  } as ToolParametersSchema,
  aliases: ["report","security_report"] as readonly string[],
};

export type SecurityReportDefinition = typeof securityReportDefinition;
