/**
 * Lightweight definition for tool "security_audit".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/audit.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const securityAuditDefinition = {
  name: "security_audit" as const,
  description: "Scans the codebase for high-risk patterns like XSS sinks, command injections, and weak crypto.",
  parameters: {
    type: 'object',
    properties: {
      path: {
        type: 'string',
        description: 'The directory or file to scan (relative to workspace root). Defaults to ".".',
      },
    },
    required: [],
  } as ToolParametersSchema,
  aliases: ["audit","security_audit"] as readonly string[],
};

export type SecurityAuditDefinition = typeof securityAuditDefinition;
