/**
 * Lightweight definition for tool "security_path_trace".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/security_path_trace.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const securityPathTraceDefinition = {
  name: "security_path_trace" as const,
  description: "Traces security-relevant source-to-sink flows in TypeScript, JavaScript, and Electron code with scope guards, caps, confidence, evidence, findings, and patch suggestions.",
  parameters: {
    type: 'object',
    properties: {
      scope: {
        type: 'string',
        description: 'Directory or file to trace, relative to workspace root. Defaults to ".".',
      },
      maxFiles: {
        type: 'number',
        description: 'Maximum code files to inspect. Defaults to 250.',
      },
      maxTraces: {
        type: 'number',
        description: 'Maximum traces to return. Defaults to 12.',
      },
      minConfidence: {
        type: 'number',
        description: 'Minimum confidence hint for caller/UI filtering. Scanner support may vary. Defaults to 0.',
      },
      mode: {
        type: 'string',
        enum: ['summary', 'full'],
        description: 'Output verbosity. Defaults to full.',
      },
    },
    required: [],
  } as ToolParametersSchema,
  aliases: ["security_path_trace"] as readonly string[],
};

export type SecurityPathTraceDefinition = typeof securityPathTraceDefinition;
