/**
 * Lightweight definition for tool "semgrep_scan".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/semgrep_scan.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const semgrepScanDefinition = {
  name: "semgrep_scan" as const,
  description: "Structural security scanner. Uses local semgrep binary or falls back to an optimized built-in pattern ruleset to detect injection, XSS, RCE, and credentials.",
  parameters: {
    type: "object",
    properties: {
      path: {
        type: "string",
        description: "The directory or file to scan (default: '.').",
      },
      ruleset: {
        type: "string",
        description: "The Semgrep ruleset to run, e.g. 'p/security-audit' or 'p/default' (default: 'p/security-audit').",
      },
      useFallbackOnly: {
        type: "boolean",
        description: "Force the use of the built-in fallback engine instead of running Semgrep.",
      },
    },
    required: [],
  } as ToolParametersSchema,
  aliases: ["semgrep_scan"] as readonly string[],
};

export type SemgrepScanDefinition = typeof semgrepScanDefinition;
