/**
 * Lightweight definition for tool "source_map_analyzer".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/source_map_analyzer.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const sourceMapAnalyzerDefinition = {
  name: "source_map_analyzer" as const,
  description: "Scans bundles and source maps for leaked public env values, secret markers, embedded source content, and risky source map exposure.",
  parameters: {
    type: "object",
    properties: {
      path: {
        type: "string",
        description:
          'Directory to scan (e.g., "dist", "build", ".next"). Defaults to ".".',
      },
      limit: {
        type: "number",
        description: "Max findings to return. Defaults to 100, capped at 500.",
      },
      contextLimit: {
        type: "number",
        description: "Max matching lines per file. Defaults to 3.",
      },
    },
  } as ToolParametersSchema,
  aliases: ["source_map_analyzer"] as readonly string[],
};

export type SourceMapAnalyzerDefinition = typeof sourceMapAnalyzerDefinition;
