/**
 * Lightweight definition for tool "sql_audit".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/sql.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const sqlAuditDefinition = {
  name: "sql_audit" as const,
  description: "Scans for SQL and NoSQL injection vulnerabilities, specifically identifying insecure query construction.",
  parameters: {
    type: "object",
    properties: {
      path: {
        type: "string",
        description:
          'The directory or file to scan (relative to workspace root). Defaults to ".".',
      },
    },
    required: [],
  } as ToolParametersSchema,
  aliases: ["sql","sql_audit"] as readonly string[],
};

export type SqlAuditDefinition = typeof sqlAuditDefinition;
