/**
 * Lightweight definition for tool "supermemory".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/supermemory.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const supermemoryDefinition = {
  name: "supermemory" as const,
  description: "Access Supermemory to store or retrieve long-term context, user preferences, and knowledge.",
  parameters: {
    type: "object",
    properties: {
      action: {
        type: "string",
        enum: ["add", "profile", "search"],
        description: "The action to perform.",
      },
      content: {
        type: "string",
        description: "The content to add (for 'add' action).",
      },
      query: {
        type: "string",
        description: "The query for searching or profile retrieval.",
      },
      containerTag: {
        type: "string",
        description:
          "The tag to isolate memory (e.g. project name or user id). Defaults to the current workspace path.",
      },
    },
    required: ["action"],
  } as ToolParametersSchema,
  aliases: ["supermemory"] as readonly string[],
};

export type SupermemoryDefinition = typeof supermemoryDefinition;
