/**
 * Lightweight definition for tool "threat_model".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/threat_model.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const threatModelDefinition = {
  name: "threat_model" as const,
  description: "Assembles architectural data to generate a high-level STRIDE threat model of the system.",
  parameters: {
    type: "object",
    properties: {}, // No params needed, scans generically
    required: [],
  } as ToolParametersSchema,
  aliases: ["threat_model"] as readonly string[],
};

export type ThreatModelDefinition = typeof threatModelDefinition;
