/**
 * Lightweight definition for tool "traffic_poison".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/traffic_poison.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const trafficPoisonDefinition = {
  name: "traffic_poison" as const,
  description: "Simulates advanced application-logic attacks (Context-Aware attacks) like HTTP Parameter Pollution, Mass Assignment, or NoSQL injections against a local sandbox. Goes beyond simple fuzzing.",
  parameters: {
    type: "object",
    properties: {
      url: {
        type: "string",
        description:
          "The local endpoint to poison (e.g., 'http://127.0.0.1:4000/api/users').",
      },
      attackType: {
        type: "string",
        description:
          "The attack vector to simulate: 'PARAMETER_POLLUTION', 'MASS_ASSIGNMENT', 'NOSQL_INJECTION', 'SSRF'.",
      },
      basePayload: {
        type: "string",
        description:
          'A valid expected JSON payload (as a string) to mutate (e.g. \'{"username":"admin"}\').',
      },
    },
    required: ["url", "attackType"],
  } as ToolParametersSchema,
  aliases: ["traffic_poison"] as readonly string[],
};

export type TrafficPoisonDefinition = typeof trafficPoisonDefinition;
