/**
 * Lightweight definition for tool "tree".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/tree.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const treeDefinition = {
  name: "tree" as const,
  description: "Generate a visual tree structure of the project directory.",
  parameters: {
    type: "object",
    properties: {
      path: {
        type: "string",
        description:
          'The root directory for the tree (relative to workspace root). Defaults to ".".',
      },
      depth: {
        type: "number",
        description: "Maximum depth of the tree. Defaults to 2.",
      },
    },
    required: [],
  } as ToolParametersSchema,
  aliases: ["tree"] as readonly string[],
};

export type TreeDefinition = typeof treeDefinition;
