/**
 * Lightweight definition for tool "verify_validation_persistence".
 * Generated by scripts/generate-tool-definitions.ts — do not load execute deps here.
 * Source: tools/validation_persistence.ts
 */
import type { ToolParametersSchema } from "../../tool-types";

export const verifyValidationPersistenceDefinition = {
  name: "verify_validation_persistence" as const,
  description: "Verifies whether the latest validation plan is persisted and whether validation runs saved that plan. Use after plan_validation and run_tests before claiming persistence.",
  parameters: {
    type: "object",
    properties: {
      runId: {
        type: "string",
        description:
          "Optional validation run ID returned by run_tests. If omitted, checks the most recent validation run.",
      },
    },
  } as ToolParametersSchema,
  aliases: ["validation_persistence"] as readonly string[],
};

export type VerifyValidationPersistenceDefinition = typeof verifyValidationPersistenceDefinition;
